version: '3.8'
services:
  app:
    build: ./app
    networks:
      - network
    container_name: app-schulshop
    ports:
      - "80:3000"
      - "3000:3000"
    depends_on:
      - redis
      # - db
    environment:
      - PRODUCTION=TRUE
      - USERNAME=username
      - PASSWORD=password
  redis:
    image: redis
    networks:
      - network
    container_name: redis-schulshop
  backend:
    build: ./backend
    networks:
      - network
    container_name: backend-schulshop
    depends_on:
      - app
      - redis
  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     - POSTGRESS_PASSWORD=admin
  #   volumes:
  #     - ./database:/var/lib/postgresql/data
  #   networks:
  #     - network
  #   container_name: db-schulshop
networks:
  network:
    driver: bridge