version: '3.8'
services:
  app:
    build: ./app
    networks:
      - network
    container_name: app-schulshop
    ports:
      - "80:3000"
      - "3000:3000"
    depends_on:
      - redis
      - database
    environment:
      - PRODUCTION=TRUE
      - USERNAME=username
      - PASSWORD=password
      - URL=127.0.0.1
  redis:
    image: redis
    networks:
      - network
    container_name: redis-schulshop
  backend:
    build: ./backend
    networks:
      - network
    container_name: backend-schulshop
    depends_on:
      - app
      - redis
  database:
    build: ./database
    networks:
      - network
    container_name: database-schulshop
networks:
  network:
    driver: bridge