version: '3.8'
services:
  app:
    build: ./app
    networks:
      - network
    container_name: app-schulshop
    ports:
      - "80:3000"
      - "3000:3000"
    depends_on:
      - redis
      # - db
    environment:
      - PRODUCTION=TRUE
  redis:
    image: redis
    networks:
      - network
    container_name: redis-schulshop
  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     - POSTGRESS_PASSWORD=admin
  #   volumes:
  #     - ./database:/var/lib/postgresql/data
  #   networks:
  #     - network
  #   container_name: db-schulshop
networks:
  network:
    driver: bridge